package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"edu_v2/graph/model"
	"edu_v2/internal/utils"
	"fmt"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
)

// CreateCollection is the resolver for the createCollection field.
func (r *mutationResolver) CreateCollection(ctx context.Context, code string, name string, file graphql.Upload) (*model.Response, error) {
	if err := utils.CheckAdminCode(code); err != nil {
		return nil, err
	}
	collection, err := utils.UploadQuestionfile(file, name)
	if err != nil {
		return nil, err
	}
	value, err := r.CollService.CreateCollection(&collection)
	return utils.AbsResponseChecking(err, strconv.Itoa(*value))
}

// UpdateCollectionActive is the resolver for the updateCollectionActive field.
func (r *mutationResolver) UpdateCollectionActive(ctx context.Context, code string, collectionID string) (*model.Response, error) {
	if err := utils.CheckAdminCode(code); err != nil {
		return nil, err
	}
	return utils.AbsResponseChecking(r.CollService.UpdateCollectionActive(collectionID), "Collection status active.")
}

// DeleteCollection is the resolver for the deleteCollection field.
func (r *mutationResolver) DeleteCollection(ctx context.Context, code string, id string) (*model.Response, error) {
	if err := utils.CheckAdminCode(code); err != nil {
		return nil, err
	}
	err := r.CollService.DeleteCollection(id)
	return utils.AbsResponseChecking(err, "Deleted")
}

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, code string, name string, teacherName string, level model.GroupLevel, startAt string, startDate string, daysWeek model.DaysWeek) (*model.Response, error) {
	if err := utils.CheckAdminCode(code); err != nil {
		return nil, err
	}
	var group model.Group
	group.Name = name
	group.TeacherName = teacherName
	group.Level = level
	group.DaysWeek = daysWeek
	group.StartedDate = startDate
	group.StartAt = startAt
	err := r.GroupService.CreateGroup(&group)
	return utils.AbsResponseChecking(err, "Group added")
}

// UpdateGroup is the resolver for the updateGroup field.
func (r *mutationResolver) UpdateGroup(ctx context.Context, code string, id string, name string, teacherName string, level model.GroupLevel, startAt string, startDate string, daysWeek model.DaysWeek) (*model.Response, error) {
	if err := utils.CheckAdminCode(code); err != nil {
		return nil, err
	}
	var group model.Group
	group.ID = id
	group.Name = name
	group.TeacherName = teacherName
	group.Level = level
	err := r.GroupService.UpdateGroup(&group)
	return utils.AbsResponseChecking(err, "updated")
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, code string, id string) (*model.Response, error) {
	if err := utils.CheckAdminCode(code); err != nil {
		return nil, err
	}
	realId, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	err = r.GroupService.DeleteGroup(realId)
	return utils.AbsResponseChecking(err, "deleted")
}

// CreateAnswer is the resolver for the createAnswer field.
func (r *mutationResolver) CreateAnswer(ctx context.Context, code string, collectionID string, answers []*string, isUpdated *bool) (*model.Response, error) {
	if err := utils.CheckAdminCode(code); err != nil {
		return nil, err
	}
	return utils.AbsResponseChecking(r.AnswerService.CreateAnswer(answers, isUpdated, &collectionID), "Answer Created")
}

// DeleteAnswer is the resolver for the deleteAnswer field.
func (r *mutationResolver) DeleteAnswer(ctx context.Context, code string, collectionID string) (*model.Response, error) {
	if err := utils.CheckAdminCode(code); err != nil {
		return nil, err
	}
	return utils.AbsResponseChecking(r.AnswerService.DeleteAnswer(&collectionID), "Answer Deleted")
}

// CreateStudentAnswer is the resolver for the createStudentAnswer field.
func (r *mutationResolver) CreateStudentAnswer(ctx context.Context, collectionID string, answers []*string, code string) (*model.Response, error) {
	return utils.AbsResponseChecking(r.AnswerService.CreateStudentAnswer(collectionID, answers, code), "Answer Saved. You can see your result on second Menu")
}

// GetGroups is the resolver for the getGroups field.
func (r *queryResolver) GetGroups(ctx context.Context, code string, byID *string, orderByLevel *bool, page *int, size *int) (*model.PaginatedResult, error) {
	if err := utils.CheckAdminCode(code); err != nil {
		utils.SendMessage(err.Error(), 6805374430)
		return nil, err
	}
	group, err := r.GroupService.GetGroup(byID, orderByLevel, page, size)
	if err != nil {
		utils.SendMessage(err.Error(), 6805374430)
		return nil, err
	}
	return group, nil
}

// GetCollection is the resolver for the getCollection field.
func (r *queryResolver) GetCollection(ctx context.Context) ([]*model.Collection, error) {
	collections, err := r.CollService.GetCollections()
	if err != nil {
		utils.SendMessage(err.Error(), 6805374430)
		return nil, err
	}
	return collections, nil
}

// GetCollectionByID is the resolver for the getCollectionById field.
func (r *queryResolver) GetCollectionByID(ctx context.Context, collectionID string) (*model.Collection, error) {
	collection, err := r.CollService.GetCollection(collectionID)
	if err != nil {
		utils.SendMessage(err.Error(), 6805374430)
		return nil, err
	}
	return collection, err
}

// GetCollectionActive is the resolver for the getCollectionActive field.
func (r *queryResolver) GetCollectionActive(ctx context.Context) (*model.Collection, error) {
	return r.CollService.GetCollectionActive()
}

// GetStudentTestExams is the resolver for the getStudentTestExams field.
func (r *queryResolver) GetStudentTestExams(ctx context.Context, code *string, studentID *string, page *int, size *int) (*model.PaginatedResult, error) {
	return r.UserCollService.GetStudentTestExams(code, studentID, page, size)
}

// GetStudentsList is the resolver for the getStudentsList field.
func (r *queryResolver) GetStudentsList(ctx context.Context, code string, page *int, size *int) (*model.PaginatedResult, error) {
	if err := utils.CheckAdminCode(code); err != nil {
		utils.SendMessage(err.Error(), 6805374430)
		return nil, err
	}
	return r.UserService.GetStudentsList(page, size)
}

// SearchStudent is the resolver for the searchStudent field.
func (r *queryResolver) SearchStudent(ctx context.Context, value string) (*model.PaginatedResult, error) {
	panic(fmt.Errorf("not implemented: SearchStudent - searchStudent"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
